### ISSUE TITLE
Uploading Bugs

### ISSUE THREAD

**Issue by jjhill4796** [domattioli/XNAT-Interact#8]
Hey Dom, I was able to get the program up and running but then ran into the following issues when trying my first upload:

1: No Options Available for Procedure/Location:

The image below shows the issue. When it asked me the surgery and the institution performed at, I didn't see the options that were available as you had shown me in our last meeting. It just had me type them in freehand. 

(.my_venv_for_xnat_interact) C:\Users\jhill\XNAT\XNAT-Interact>python main.py
======================================================================================================================================================
HawkID Username: jhill7
HawkID Password: ****************
        --Successfully logged in as 'jhill7'!
======================================================================================================================================================

Enter 1, 2, or 3 to choose a function:
        1. Upload new source data to XNAT.
        2. Upload derived data for existing source data to XNAT.
        3. Download queried data from XNAT.
                Selection --> 1

Uploading new source data to XNAT...
        Required inputs:
                Input Directory:                D:\All_Data
                Group (surgical procedure):     Knee Arthroscopy
                Acquisition Site:               University of Iowa

2: After entering the acquisition site, it looks like XNAT tried to start uploading data on its own without requesting any other information, then the program just timed out. Here's what that looked like:

(.my_venv_for_xnat_interact) C:\Users\jhill\XNAT\XNAT-Interact>python main.py
======================================================================================================================================================
HawkID Username: jhill7
HawkID Password: ****************
        --Successfully logged in as 'jhill7'!
======================================================================================================================================================

Enter 1, 2, or 3 to choose a function:
        1. Upload new source data to XNAT.
        2. Upload derived data for existing source data to XNAT.
        3. Download queried data from XNAT.
                Selection --> 1

Uploading new source data to XNAT...
        Required inputs:
                Input Directory:                D:\All_Data
                Group (surgical procedure):     Knee Arthroscopy
                Acquisition Site:               University of Iowa
-- XNAT Connection --
Status:         Closed
Signed-in:      jhill7
Project:        None

Now processing "SourceRFSession" for "D:\All_Data" ...
                                                    FN   EXT NEW_FN DICOM  ... DATE SERIES_TIME INSTANCE_TIME INSTANCE_NUM
0                           Case5_6-12_730_Arthro_Knee          NaN   NaN  ...  NaN         NaN           NaN          NaN
1                       Case6_6-12_841_Arthro_Shoulder          NaN   NaN  ...  NaN         NaN           NaN          NaN
2                          Case8_6-12_1311_Arthro_Knee          NaN   NaN  ...  NaN         NaN           NaN          NaN
3                           Case9_6-13_730_Arthro_Knee          NaN   NaN  ...  NaN         NaN           NaN          NaN
4                          Case10_6-13_840_Arthro_Knee          NaN   NaN  ...  NaN         NaN           NaN          NaN
..                                                 ...   ...    ...   ...  ...  ...         ...           ...          ...
534  10872618_KneeArthroscopy_2024-07-01-073342_Wes...  .jpg    NaN   NaN  ...  NaN         NaN           NaN          NaN
535  10872618_KneeArthroscopy_2024-07-01-073342_Wes...  .jpg    NaN   NaN  ...  NaN         NaN           NaN          NaN
536  10872618_KneeArthroscopy_2024-07-01-073342_Wes...  .jpg    NaN   NaN  ...  NaN         NaN           NaN          NaN
537  10872618_KneeArthroscopy_2024-07-01-073342_Wes...  .jpg    NaN   NaN  ...  NaN         NaN           NaN          NaN
538  10872618_KneeArthroscopy_2024-07-01-073342_Wes...  .jpg    NaN   NaN  ...  NaN         NaN           NaN          NaN

[539 rows x 9 columns]
***Session is invalid; could be for several reasons. try evaluating whether all of the image hash_strings already exist in the matatable.
Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\main.py", line 63, in upload_new_case
    zipped_ffn = source_images.write( print_out=True )
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\src\DataTypes.py", line 603, in write
    assert os.path.isdir( zip_dest ), 'Destination for zipped folder must be an existing directory; you entered: {zip_dest}'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Destination for zipped folder must be an existing directory; you entered: {zip_dest}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000131C51CF5F0>, 'Connection to rpacs.iibi.uiowa.edu timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\adapters.py", line 589, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rpacs.iibi.uiowa.edu', port=443): Max retries exceeded with url: /xnat//data/JSESSION (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000131C51CF5F0>, 'Connection to rpacs.iibi.uiowa.edu timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\main.py", line 78, in <module>
    main()
  File "C:\Users\jhill\XNAT\XNAT-Interact\main.py", line 46, in main
    upload_new_case( validated_login=validated_login, metatables=metatables )
  File "C:\Users\jhill\XNAT\XNAT-Interact\main.py", line 60, in upload_new_case
    with XNATConnection( validated_login, metatables ) as connection:
  File "C:\Users\jhill\XNAT\XNAT-Interact\src\Utilities.py", line 466, in __exit__
    def __exit__( self, exc_type, exc_value, traceback ): self.close()
                                                          ^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\src\Utilities.py", line 458, in close
    self._server.disconnect()
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 500, in disconnect
    self._exec('/data/JSESSION', method='DELETE')
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 336, in _exec
    response = request(method, uri, headers, body, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 326, in request
    response = self._http.delete(uri, headers=headers, data=body,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 671, in delete
    return self.request("DELETE", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\adapters.py", line 610, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rpacs.iibi.uiowa.edu', port=443): Max retries exceeded with url: /xnat//data/JSESSION (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000131C51CF5F0>, 'Connection to rpacs.iibi.uiowa.edu timed out. (connect timeout=None)'))
Exception ignored in: <function XNATConnection.__del__ at 0x00000131C44B2E80>
Traceback (most recent call last):
  File "C:\Users\jhill\XNAT\XNAT-Interact\src\Utilities.py", line 462, in __del__
  File "C:\Users\jhill\XNAT\XNAT-Interact\src\Utilities.py", line 458, in close
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 500, in disconnect
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 336, in _exec
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\pyxnat\core\interfaces.py", line 326, in request
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 671, in delete
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\sessions.py", line 703, in send
  File "C:\Users\jhill\XNAT\XNAT-Interact\.my_venv_for_xnat_interact\Lib\site-packages\requests\adapters.py", line 610, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rpacs.iibi.uiowa.edu', port=443): Max retries exceeded with url: /xnat//data/JSESSION (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000131C469F530>, 'Connection to rpacs.iibi.uiowa.edu timed out. (connect timeout=None)'))

(.my_venv_for_xnat_interact) C:\Users\jhill\XNAT\XNAT-Interact>

**Comment by domattioli** [comment]
Closing this because it resulted from depracated code from months ago and I do not recall what the solution was that Jared and I determined from an in-person meeting.
